
QUBERSHIP-APIHUB_VERSION: dev
IMAGE_REPOSITORY: #TO_BE_SET
TAG: #TO_BE_SET
ARTIFACT_DESCRIPTOR_VERSION: #TO_BE_SET
PAAS_PLATFORM: "KUBERNETES"
PAAS_VERSION: '1.29'
CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname
APIHUB_REPLICAS: 1
PART_OF: 'API-HUB'
DELIMITER: '-'
NAMESPACE: '' #TO_BE_SET
LOG_LEVEL: "INFO"
PRODUCTION_MODE: false
APIHUB_ACCESS_TOKEN: 'uHw6L2LnuxY5z46qcVnN7fv7zaW6FpthbuG8wVYeYmYKzQjGeddVeFwdDHy1zGyB'
LDAP_SERVER: ''
LDAP_USER: ''
LDAP_USER_PASSWORD: ''
MANAGED_BY: 'saasDeployer'
ADFS_METADATA_URL: '' #TO_BE_SET
APIHUB_URL: '' #TO_BE_SET

SAML_CRT: ''
SAML_KEY: ''
EXTERNAL_LINKS: ''
DEFAULT_WORKSPACE_ID: ''

RELEASE_VERSION_PATTERN: '^[0-9]{4}[.]{1}[1-4]{1}$'
JWT_PRIVATE_KEY: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ1ZpTlJ3cVRZaFZyekkKZjhQM2g4SWJrd3dRQUY1bW41NnZCT21YbTZTUWdsOGQwQTI5VXlvSVRicmJtbVNJeE11NjEyaHJMMVJzdmlMTwo2OXBJUTd6cU9qOC9Xd3FRSzNaNTNWTGcycG5ncG1YTXRFQ3RqVFR6QWJTR0xsdklqdm1iSGhZdnhHdDFaY2lTCkYwdjNVb3RJUTFmRm9UWkdkQ205cXFWaU1pYUJFUFAya0QzVlExbFMwQ1crbWFTUmJUZ1pjR1pxb3ZUdG5zUDkKODhHRTRhZTc1QkptS2lCeVdjZGpJTlFxaTFyTFRDNVJQdGhtYWdUMVFhYTVZQmFBdy9QY1M3VnJwYS9QS0JzNwpQdTBZZUNLa3lyOGxXNDFYU29OQkJ3ZlNvbmhnUG14MUNmaStBdXFRMEF6VWxJNURScWFyWndIc2Q0UGh4SHJkCjcxNWp5R0h6QWdNQkFBRUNnZ0VBSm0vcm02SURSZ0tUdUQ0UFUzdFVDOTU2aFVweStaSWlLZjdyUklzL2U5M24KTVRTZnM0RERGeXRUMHNzVytJa05qVk45aGIrK3hjMENDWXBhcTZTdDFNOXdIb3I2WmlDbDdhRlVnblB1aGU1LwowR1N0RTI5dW91QlhWUDVwblY0VER5cG1yWlNod3FXTkx2QktHS0xoSm93WTdiWUl5NGRraTFwbjlKdkxoZlUrCjZCcm9SS0NMVzNWZlNSbVExRkd2QzhLR2daTGh4am9panVVemhIdkJxRVYxaERraU5GdzNQMjl5Ui8vQkU2VVkKbkRLZ1lNUmRRWXY3ZkFld095OHJ4RTBTS3ZiVUxOUXAxb2IxNHMxWlZGU1R4SWtvN2RYV1l0U0FwUENwdFp5bgpHVC91eG0xZnErSlhJQnI4OXFPSmlBcFBBMFVYWHM5czBITXRXTGdkSVFLQmdRRE9Ebkl2N1NaemhPdGpnSTV3Cm91WmFPRzNva3puS0xrMGp5RUQrWWhpQ2lGM1diNnZnZnUxbUh4M3NnRVp3Z2hnTTJMVERhOXpTWGV5RmpRRDAKcjNXcUM2NFNxMWdhUVVQejJ6bUVOdk8wRGdKN3pkMUVKTURxZGJacllLQUs4NUJ3ZmsvcTJoc1prM2Z5SHl4dwprZ1RzZzM0NkJGZVpsVnFGL0N0MkpnSVdtUUtCZ1FDNXgwUHkzVENBV2p5OEw5NGhrMzM0b2hwUXpDeTVxeXR3CnVHUklCTXlFVE9wNU5hUFBIQVdnbEZ3YzFMSis4bldmckZjeUEySjIrZ2V6K0ovOG1uU2hPNjF1MXVaNVV3dVkKQUQyaFlwUFcxMzJHZG9LcnI1ZkplVDJJUmR2bzRHa2FXN1Q2YnV1MGhjNzB0ZXZ4eDcxc2llWVBWaTBRenRGcgpnZSswNFBad2F3S0JnUUM2c1JnQUdFdklTbHZDOFUwYy9GcmN6MWUxYXY3bkVnQk9OVGU5d3o4VnRWdmYxNW5RCmN1L0FvTnpKMUliOWxNRVprcFprb0t1WDVnVlFFeXNVaG95REhzWCtvRVBZdGQxTmFnaTRvOWsxLzZOOGJFN1gKV0wxNU1HR3c5QUROSzFSb3Qrak1qZ1FUcmlyMHNnM2ZpRXp4eFVsdVkxVERFRERPU0dWUVRLdURzUUtCZ1FDcgpFUFRkbnBWNXF4My8vMmZnclFxek5ybGFxeGVJQkRqays3WERweitYbDZmVTR2S3ExRmZPTEs3QkVZNG5YU1c0CldSNlZmQTVnRmcyZnlCR3hyWncxbDFrMUZnZDFzbVdibXFVbGhUc3krb3lvazFueHM2Zm1LcERoZWNwc25xL0oKU0tiV2IrcjArTDNBRWdCb1M0OStjV0I1d05XUWc1RE5HUUhjSWNacmJ3S0JnRmV4a1JWUU1sZE5NVjFrTHFyMApSVzdXWTVIRk1XcnRJVkNacTZzRVIzT2NCR2xUaE9XNnpGcUJMK1pmODUzdmRtK3h6OG5ZRXRaSktiYmM3Yi9iClFQc0Uzay9FZFBRbSt4S214Y2hHQUg5ZFg0eUM5OEViSjMvc25TekxGYUpGdWdnMjArQWRxY3hNa1ZnaWhMVEMKWW1teTdTREY5OXRackxrT0dab2ZvSml4Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0='


#####apihub-backend 
MEMORY_LIMIT: "512Mi"
CPU_REQUEST: "100m"
CPU_LIMIT: "1"

SERVICE: "apihub-backend"
SERVICE_NAME: "apihub-backend"
DEPLOYMENT_RESOURCE_NAME: "apihub-backend"

SERVICE_ACCOUNT: "apihub-backend"
SERVICE_ACCOUNT_APIHUB_SECRET_NAME: "apihub-backend-secret"

DIFF_SERVICE_URL: "http://apihub-node-service:3000"
GITLAB_URL: "https://git.netcracker.com" #TO_BE_SET

DB_TYPE: "postgres"
APIHUB_POSTGRESQL_HOST: "pg-common"
APIHUB_POSTGRESQL_PORT: "5432"
APIHUB_POSTGRESQL_ADMIN_USERNAME: '' #TO_BE_SET
APIHUB_POSTGRESQL_ADMIN_PASSWORD: '' #TO_BE_SET
APIHUB_POSTGRESQL_DB_NAME: '' #TO_BE_SET
APIHUB_POSTGRESQL_USERNAME: '' #TO_BE_SET
APIHUB_POSTGRESQL_PASSWORD: '' #TO_BE_SET
APIHUB_SKIP_DB_CREATION: true



PUBLISH_ARCHIVE_SIZE_LIMIT_MB: "50"
PUBLISH_FILE_SIZE_LIMIT_MB: "15"

CLIENT_ID: '' #TO_BE_SET
CLIENT_SECRET: '' #TO_BE_SET

ORIGIN_ALLOWED: '' #TO_BE_SET


SYSTEM_NOTIFICATION: ''
INSECURE_PROXY: true

MONITORING_ENABLED: false

STORAGE_SERVER_USERNAME: ''
STORAGE_SERVER_PASSWORD: ''
STORAGE_SERVER_CRT: ''
STORAGE_SERVER_URL: ''
STORAGE_SERVER_BUCKET_NAME: ''
STORAGE_SERVER_ACTIVE: false
STORAGE_SERVER_STORE_ONLY_BUILD_RESULT: true

APIHUB_ADMIN_EMAIL: 'x_APIHUB'
APIHUB_ADMIN_PASSWORD: 'Tmf@c23s'



#####apihub-node-service

"MEMORY_LIMIT": "4200Mi"
"MEMORY_REQUEST": "750Mi"
CPU_REQUEST: "100m"
CPU_LIMIT: "1.25"
REPLICAS: 1


SERVICE: "apihub-node-service"
SERVICE_NAME: "apihub-node-service"
DEPLOYMENT_RESOURCE_NAME: "apihub-node-service"

SERVICE_ACCOUNT: "apihub-node-service"
SERVICE_ACCOUNT_APIHUB_SECRET_NAME: "apihub-node-service"

APIHUB_BACKEND_ADDRESS: "apihub-backend:8080"
FOLDER_STORE: "/tmp"
OPERATIONS_BUILD_BATCH: "16"
 
#####apihub-ui 
# Names
SERVER_HOSTNAME: ''
SERVICE: "apihub-ui"
SERVICE_NAME: "apihub-ui"
DEPLOYMENT_RESOURCE_NAME: "apihub-ui"

# SSL
CERTIFICATE_BUNDLE_MD5SUM: "d41d8cd98f00b204e9800998ecf8427e"
SSL_SECRET: "defaultsslcertificate"

# Run params and limits
CPU_LIMIT: 1
CPU_REQUEST: "30m"
MEMORY_LIMIT: "64Mi"
MEMORY_REQUEST: "64Mi"
REPLICAS: 1

DNS_ROUTE_ENABLE: false
TLS_CRT: ''
TLS_KEY: ''
DNS_ROUTE: ''

# Docker repository

APIHUB_NC_SERVICE_ADDRESS: "apihub-nc-service:8080"
APIHUB_BACKEND_ADDRESS: "apihub-backend:8080"

