---
apiVersion: v1
kind: Secret
metadata:
    name: '{{ .Values.SERVICE_ACCOUNT_APIHUB_SECRET_NAME }}'
    namespace: '{{ .Values.NAMESPACE }}'
    annotations:
        kubernetes.io/service-account.name: 'qubership-apihub-build-task-consumer'
    labels:
        app.kubernetes.io/part-of: qubership-apihub
        app.kubernetes.io/managed-by: helm
type: kubernetes.io/service-account-token

