apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: apihub
    annotations:
        nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
        nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
        nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    labels:
        app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
        app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
        deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
spec:
    rules:
        -   host: 'apihub-{{ .Values.NAMESPACE }}.{{ .Values.SERVER_HOSTNAME }}'
            http:
                paths:
                    -   path: /
                        pathType: Prefix
                        backend:
                            service:
                                name: '{{ .Values.SERVICE_NAME }}'
                                port:
                                    name: web
