apiVersion: v1
stringData:
  apihub_postgresql_username: {{ if (default "" .Values.APIHUB_POSTGRESQL_USERNAME) }} '{{ .Values.APIHUB_POSTGRESQL_USERNAME }}' {{ else }} '{{ cat .Values.SERVICE_NAME .Values.DELIMITER .Values.NAMESPACE .Values.DELIMITER "admin" | nospace | replace "-" "_" }}' {{ end }}
  apihub_postgresql_password: {{ if (default "" .Values.APIHUB_POSTGRESQL_PASSWORD) }} '{{ .Values.APIHUB_POSTGRESQL_PASSWORD }}' {{ else }} '{{ cat .Values.SERVICE_NAME .Values.DELIMITER .Values.NAMESPACE .Values.DELIMITER "password" | nospace | replace "-" "_" }}' {{ end }}
kind: Secret
metadata:
  name: '{{ .Values.SERVICE }}-db-secret'
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
type: Opaque

