---
kind: Service
apiVersion: v1
metadata:
    name: qubership-apihub-ui
    labels:
        name: qubership-apihub-ui
        app.kubernetes.io/name: 'qubership-apihub-ui'
        app.kubernetes.io/version: '{{ .Values.QUBERSHIP_APIHUB_VERSION }}'
        app.kubernetes.io/part-of: qubership-apihub
        app.kubernetes.io/managed-by: helm
spec:
    ports:
    -   name: web
        port: 8080
        targetPort: 8080
    selector:
      name: qubership-apihub-ui

