apiVersion: v1
stringData:
  access_token: '{{ .Values.APIHUB_ACCESS_TOKEN }}'
kind: Secret
metadata:
  name: '{{ .Values.SERVICE }}-api-key-secret'
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
type: Opaque

