{{- if .Values.qubership-apihub-ui.dns-ingress.enabled }}
apiVersion: v1
data:
  tls.crt: '{{ .Values.qubership-apihub-ui.dns-ingress.tls-secret.tls-certificate }}'
  tls.key: '{{ .Values.qubership-apihub-ui.dns-ingress.tls-secret.tls-certificate-key }}'
kind: Secret
metadata:
  name: 'qubership-apihub-ui-tls'
  namespace: '{{ .Values.qubership-apihub.namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque
{{- end }}