apiVersion: v1
stringData:
  ldap_user: '{{ .Values.LDAP_USER }}'
  ldap_user_password: '{{ .Values.LDAP_USER_PASSWORD }}'
kind: Secret
metadata:
  name: '{{ .Values.SERVICE }}-ldap-user-secret'
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
type: Opaque