apiVersion: v1
stringData:
  apihub_postgresql_username: {{ if (default "" .Values.qubership-apihub-backend.env.db-admin-username) }} '{{ .Values.qubership-apihub-backend.env.db-admin-username }}' {{ else }} '{{ cat qubership-apihub-backend .Values.qubership-apihub.delimiter .Values.qubership-apihub.namespace .Values.qubership-apihub.delimiter "admin" | nospace | replace "-" "_" }}' {{ end }}
  apihub_postgresql_password: {{ if (default "" .Values.qubership-apihub-backend.env.db-admin-password) }} '{{ .Values.qubership-apihub-backend.env.db-admin-password }}' {{ else }} '{{ cat qubership-apihub-backend .Values.qubership-apihub.delimiter .Values.qubership-apihub.namespace .Values.qubership-apihub.delimiter "password" | nospace | replace "-" "_" }}' {{ end }}
kind: Secret
metadata:
  name: 'qubership-apihub-backend-db-secret'
  namespace: '{{ .Values.qubership-apihub.namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque

