apiVersion: v1
stringData:
  token: '{{ .Values.APIHUB_ACCESS_TOKEN }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-access-token-secret'
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
      app.kubernetes.io/part-of: qubership-apihub
      app.kubernetes.io/managed-by: helm
type: Opaque