{{- if .Values.DNS_ROUTE_ENABLE }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: apihub-tls
    annotations:
        nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
        nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
        nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    labels:
        app.kubernetes.io/part-of: qubership-apihub
        app.kubernetes.io/managed-by: helm
spec:
    tls:
        - hosts:
            - '{{ .Values.DNS_ROUTE }}'
          secretName: 'qubership-apihub-ui-tls'
    rules:
        -   host: '{{ .Values.DNS_ROUTE }}'
            http:
                paths:
                    -   path: /
                        pathType: Prefix
                        backend:
                            service:
                                name: 'qubership-apihub-ui'
                                port:
                                    name: web
{{- end }}
