---
apiVersion: v1
kind: Secret
metadata:
    name: '{{ .Values.SERVICE_ACCOUNT_APIHUB_SECRET_NAME }}'
    namespace: '{{ .Values.NAMESPACE }}'
    annotations:
        kubernetes.io/service-account.name: '{{ .Values.SERVICE_ACCOUNT }}'
    labels:
        app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
        app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
        deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
type: kubernetes.io/service-account-token

