apiVersion: v1
stringData:
  storage_server_access_key_id: '{{ .Values.STORAGE_SERVER_USERNAME }}'
  storage_server_secret_access_key: '{{ .Values.STORAGE_SERVER_PASSWORD }}'
  storage_server_crt: '{{ .Values.STORAGE_SERVER_CRT }}'
  storage_server_endpoint: '{{ .Values.STORAGE_SERVER_URL }}'
  storage_server_bucket_name: '{{ .Values.STORAGE_SERVER_BUCKET_NAME }}'
  storage_server_active: '{{ .Values.STORAGE_SERVER_ACTIVE }}'
  storage_server_store_only_build_result: '{{ .Values.STORAGE_SERVER_STORE_ONLY_BUILD_RESULT }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-storage-secret'
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque