apiVersion: v1
stringData:
  storage_server_access_key_id: '{{ .Values.qubership-apihub-backend.env.storage-server.storage-server-username }}'
  storage_server_secret_access_key: '{{ .Values.qubership-apihub-backend.env.storage-server.storage-server-password }}'
  storage_server_crt: '{{ .Values.qubership-apihub-backend.env.storage-server.storage-server-crt }}'
  storage_server_endpoint: '{{ .Values.qubership-apihub-backend.env.storage-server.storage-server-url }}'
  storage_server_bucket_name: '{{ .Values.qubership-apihub-backend.env.storage-server.storage-server-bucket-name }}'
  storage_server_active: '{{ .Values.qubership-apihub-backend.env.storage-server.storage-server-active }}'
  storage_server_store_only_build_result: '{{ .Values.qubership-apihub-backend.env.storage-server.storage-server-store-only-build-result }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-storage-secret'
  namespace: '{{ .Values.qubership-apihub.namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque