apiVersion: v1
stringData:
  saml_crt: '{{ .Values.SAML_CRT }}'
  saml_key: '{{ .Values.SAML_KEY }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-saml-secret'
  namespace: '{{ .Values.qubership-apihub.namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque