---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: 'qubership-apihub-backend'
    labels:
        name: 'qubership-apihub-backend'
        app.kubernetes.io/name: 'qubership-apihub-backend'
        app.kubernetes.io/version: '{{ .Values.qubership-apihub.version }}'
        app.kubernetes.io/component: 'backend'
        app.kubernetes.io/part-of: qubership-apihub
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/technology: 'go'
spec:
    replicas: {{ .Values.qubership-apihub-backend.replicas }}
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
    template:
        metadata:
            labels:
                name: 'qubership-apihub-backend'
                app.kubernetes.io/name: 'qubership-apihub-backend'
                app.kubernetes.io/version: '{{ .Values.qubership-apihub.version }}'
                app.kubernetes.io/component: 'backend'
                app.kubernetes.io/part-of: qubership-apihub
                app.kubernetes.io/managed-by: helm
                app.kubernetes.io/technology: 'go'
        spec:
            serviceAccountName: 'qubership-apihub-backend'
            volumes:
            -   configMap:
                    defaultMode: 420
                    name: qubership-apihub-config
                name: qubership-apihub-config
            containers:
            -   name: 'qubership-apihub-backend'
                image: '{{ .Values.qubership-apihub-backend.image-repository }}:{{ .Values.qubership-apihub-backend.tag }}'
                volumeMounts:
                -   name: qubership-apihub-config
                    mountPath: /app/qubership-apihub-service/etc/
                    readOnly: true
                ports:
                -   name: web
                    containerPort: 8080
                    protocol: TCP
                -   name: olric
                    containerPort: 3320
                    protocol: TCP
                -   name: memberlist
                    containerPort: 3322
                    protocol: TCP
                env:
                -   name: production-mode
                    value: '{{ .Values.qubership-apihub-backend.env.production-mode  }}'
                -   name: log-level
                    value: '{{ .Values.qubership-apihub.log-level }}'
#                -   name: artifact-descriptor-version
#                    value: '{{ .Values.ARTIFACT_DESCRIPTOR_VERSION }}'
                -   name: DIFF_SERVICE_URL
                    value: '{{ .Values.qubership-apihub-backend.env.diff-service-url }}'
                -   name: GITLAB_URL
                    value: '{{ .Values.qubership-apihub-backend.env.gitlab-url }}'
                -   name: db-type
                    value: '{{ .Values.qubership-apihub-backend.env.db-type }}'
                -   name: APIHUB_POSTGRESQL_HOST
                    value: '{{ .Values.qubership-apihub-backend.env.db-host }}'
                -   name: APIHUB_POSTGRESQL_PORT
                    value: '{{ .Values.qubership-apihub-backend.env.db-port }}'
                -   name: APIHUB_POSTGRESQL_DB_NAME
                    value: {{ if (default "" .Values.qubership-apihub-backend.env.db-name) }} '{{ .Values.qubership-apihub-backend.env.db-name }}' {{ else }} '{{ cat qubership-apihub-backend .Values.qubership-apihub.delimiter .Values.qubership-apihub.namespace .Values.qubership-apihub.delimiter "db" | nospace | replace "-" "_" }}' {{ end }}
                -   name: APIHUB_POSTGRESQL_USERNAME
                    valueFrom:
                      secretKeyRef:
                         name: 'qubership-apihub-backend-db-secret'
                         key: apihub_postgresql_username
                -   name: APIHUB_POSTGRESQL_PASSWORD
                    valueFrom:
                      secretKeyRef:
                         name: 'qubership-apihub-backend-db-secret'
                         key: apihub_postgresql_password
                -   name: NAMESPACE
                    valueFrom:
                        fieldRef:
                            fieldPath: metadata.namespace
                -   name: OLRIC_DISCOVERY_MODE
                    value: 'lan'
                -   name: OLRIC_REPLICA_COUNT
                    value: '{{ .Values.qubership-apihub-backend.replicas }}'
                -   name: ADFS_METADATA_URL
                    value: '{{ .Values.qubership-apihub-backend.env.adfs-metadata-url }}'
                -   name: APIHUB_URL
                    value: {{ if (default "" .Values.qubership-apihub-backend.env.apihub-url) }} '{{ .Values.qubership-apihub-backend.env.apihub-url }}' {{ else }} 'https://apihub-{{ .Values.qubership-apihub.namespace }}.{{ .Values.qubership-apihub-ui.server-hostname }}' {{ end }}
                -   name: SAML_CRT
                    valueFrom:
                      secretKeyRef:
                         name: 'qubership-apihub-backend-saml-secret'
                         key: saml_crt
                -   name: SAML_KEY
                    valueFrom:
                      secretKeyRef:
                         name: 'qubership-apihub-backend-saml-secret'
                         key: saml_key
                -   name: EXTERNAL_LINKS
                    value: '{{ .Values.qubership-apihub-backend.env.external-links }}'
                -   name: DEFAULT_WORKSPACE_ID
                    value: '{{ .Values.qubership-apihub-backend.env.default-workspace-id }}'
                -   name: RELEASE_VERSION_PATTERN
                    value: '{{ .Values.qubership-apihub-backend.env.release-version-pattern }}'
                -   name: JWT_PRIVATE_KEY
                    valueFrom:
                      secretKeyRef:
                         name: 'qubership-apihub-backend-jwt-secret'
                         key: jwt_private_key
                -   name: CLIENT_ID
                    valueFrom:
                      secretKeyRef:
                         name: 'qubership-apihub-backend-gitlab-secret'
                         key: client_id
                -   name: CLIENT_SECRET
                    valueFrom:
                      secretKeyRef:
                         name: 'qubership-apihub-backend-gitlab-secret'
                         key: client_secret
                -   name: PUBLISH_FILE_SIZE_LIMIT_MB
                    value: '{{ .Values.qubership-apihub-backend.env.publish-file-size-limit-mb }}'
                -   name: PUBLISH_ARCHIVE_SIZE_LIMIT_MB
                    value: '{{ .Values.qubership-apihub-backend.env.publish-archive-size-limit-mb }}'
                -   name: ORIGIN_ALLOWED
                    value: '{{ .Values.qubership-apihub-backend.env.origin-allowed }}'
                -   name: LDAP_SERVER
                    value: '{{ .Values.qubership-apihub-backend.env.ldap.ldap-server }}'
                -   name: LDAP_USER
                    valueFrom:
                      secretKeyRef:
                         name: 'qubership-apihub-backend-ldap-user-secret'
                         key: ldap_user
                -  name: LDAP_USER_PASSWORD
                   valueFrom:
                     secretKeyRef:
                        name: 'qubership-apihub-backend-ldap-user-secret'
                        key: ldap_user_password
                -  name: system-notification
                   value: '{{ .Values.qubership-apihub-backend.system-notification }}'
                -  name: insecure-proxy
                   value: '{{ .Values.qubership-apihub-backend.insecure-proxy }}'
                - name: monitoring-enabled
                  value: '{{ .Values.qubership-apihub-backend.monitoring-enabled }}'
                - name: STORAGE_SERVER_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: 'qubership-apihub-backend-storage-secret'
                      key: storage_server_access_key_id
                - name: STORAGE_SERVER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: 'qubership-apihub-backend-storage-secret'
                      key: storage_server_secret_access_key
                - name: STORAGE_SERVER_CRT
                  valueFrom:
                    secretKeyRef:
                      name: 'qubership-apihub-backend-storage-secret'
                      key: storage_server_crt
                - name: STORAGE_SERVER_URL
                  valueFrom:
                    secretKeyRef:
                      name: 'qubership-apihub-backend-storage-secret'
                      key: storage_server_endpoint
                - name: STORAGE_SERVER_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: 'qubership-apihub-backend-storage-secret'
                      key: storage_server_bucket_name
                - name: STORAGE_SERVER_ACTIVE
                  valueFrom:
                    secretKeyRef:
                      name: 'qubership-apihub-backend-storage-secret'
                      key: storage_server_active
                - name: STORAGE_SERVER_STORE_ONLY_BUILD_RESULT
                  valueFrom:
                    secretKeyRef:
                      name: 'qubership-apihub-backend-storage-secret'
                      key: storage_server_store_only_build_result
                -   name: APIHUB_ADMIN_EMAIL
                    valueFrom:
                      secretKeyRef:
                        name: 'qubership-apihub-backend-zero-day-admin-secret'
                        key: apihub_admin_email
                -  name: APIHUB_ADMIN_PASSWORD
                   valueFrom:
                     secretKeyRef:
                       name: 'qubership-apihub-backend-zero-day-admin-secret'
                       key: apihub_admin_password
                -  name: APIHUB_ACCESS_TOKEN
                   valueFrom:
                     secretKeyRef:
                       name: 'qubership-apihub-backend-access-token-secret'
                       key: token
                -   name: APIHUB_SKIP_DB_CREATION
                    value: '{{ .Values.qubership-apihub-backend.env.skip-db-creation }}'
                resources:
                    requests:
                        cpu: {{ .Values.qubership-apihub-backend.resource.cpu.request }}
                        memory: '{{ .Values.qubership-apihub-backend.resource.memory.limit }}'
                    limits:
                        cpu: {{ .Values.qubership-apihub-backend.resource.cpu.limit }}
                        memory: '{{ .Values.qubership-apihub-backend.resource.memory.limit }}'
                livenessProbe:
                    httpGet:
                        path: /live
                        port: web
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    timeoutSeconds: 2
                    failureThreshold: 2
                readinessProbe:
                    httpGet:
                        path: /ready
                        port: web
                    initialDelaySeconds: 5
                    periodSeconds: 5
                    timeoutSeconds: 2
                securityContext:
                {{ if eq .Values.qubership-apihub.paas-platform "KUBERNETES" }}
                    runAsGroup: 10001
                {{ end }}
                    readOnlyRootFilesystem: false
                    runAsNonRoot: true
                    seccompProfile:
                        type: RuntimeDefault
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                          - ALL
    selector:
        matchLabels:
            name: 'qubership-apihub-backend'

