apiVersion: v1
stringData:
  jwt_private_key: '{{ .Values.qubership-apihub-backend.env.jwt-private-key }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-jwt-secret'
  namespace: '{{ .Values.qubership-apihub.namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque