{{ if .Values.MONITORING_ENABLED }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: 'monitoring'
    app.kubernetes.io/managed-by: saasDeployer
    app.kubernetes.io/processed-by-operator: victoriametrics-operator
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}-monitor'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
    k8s-app: '{{ .Values.SERVICE_NAME }}-monitor'
  name: '{{ .Values.SERVICE_NAME }}-monitor'
spec:
  targetLabels:
    - domain
  endpoints:
    - interval: 30s
      path: '/metrics'
      port: web
      scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - {{ .Values.NAMESPACE }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.SERVICE_NAME }}
---
  {{end}}