---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: 'qubership-apihub-backend'
    namespace: '{{ .Values.NAMESPACE }}'
    labels:
        app.kubernetes.io/part-of: qubership-apihub
        app.kubernetes.io/managed-by: helm

